//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosiness.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CosinessEntities : DbContext
    {
        private static CosinessEntities _context;
        public CosinessEntities()
            : base("name=CosinessEntities")
        {
        }
        public static CosinessEntities GetContext()
        {
            if (_context == null)
            {
                _context = new CosinessEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_List> Order_List { get; set; }
        public virtual DbSet<Order_status> Order_status { get; set; }
        public virtual DbSet<Pick_up_Point> Pick_up_Point { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
