//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosiness.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_List = new HashSet<Order_List>();
        }
    
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int Order_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<int> Point_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_List> Order_List { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual Pick_up_Point Pick_up_Point { get; set; }
        public virtual User User { get; set; }
    }
}
